server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: MoodHolic
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  #    hibernate:
  #      ddl-auto: create
  profiles:
    active: private


